from cryptography.hazmat.primitives import serialization

# on the laptop, open the private key generated by keypair
with open('private_key.pem', 'rb') as f:
    private_key = serialization.load_pem_private_key(
        f.read(),
        password=None
    )
